### ISSUE TITLE
I am unable to get the receiver message

### ISSUE THREAD

**Issue by rajan-dev** [instamobile/messenger-iOS-chat-swift-firestore#12]
I have downloaded code and update the pod. Integrated GoogleInfo.plist in the source code. When I run the code, I am able to send the message and message is storing on firebase database, while unable to get message of receiver if receiver reply for my message. Please suggest what am I missing. I am using two different simulator with different sender and receiverID.

**Comment by fury21** [comment]
Same problem

**Comment by awanidanijoshi** [comment]
Same issue. Did you find a solution for this?

**Comment by mrcflorian** [comment]
Hey everyone, can you check now? @DuyBui297 just submitted a fix

**Comment by awanidanijoshi** [comment]
@DuyBui297  and @mrcflorian: Its working now. Thank for fixing the issue so quickly! :)
