### ISSUE TITLE
Unable to find GroupChat

### ISSUE THREAD

**Issue by shubham-NIIT** [instamobile/messenger-iOS-chat-swift-firestore#18]
Hello 

I am unable to find the group chat code in the codebase.

Please let me know if I am missing something.

Thanks

**Comment by mrcflorian** [comment]
Unfortunately this open source project doesn't include group chats, since that's included in our [pro version](https://www.iosapptemplates.com/templates/chat-ios-app-template-swift-firebase) (along with many other features).
