### ISSUE TITLE
Use of unresolved identifier 'ATCChatUIConfiguration'

### ISSUE THREAD

**Issue by merovic** [instamobile/messenger-iOS-chat-swift-firestore#4]
I am sure i successfully imported Core folder to my Xcode project but the provided code snippet still gives error

**Comment by mrcflorian** [comment]
@merovic can you share the error with us?

**Comment by merovic** [comment]
Use of unresolved identifier 'ATCChatUIConfiguration'
Use of unresolved identifier 'ATCChatChannel'
Use of unresolved identifier 'ATCUser'
Use of unresolved identifier 'ATCChatThreadViewController'

**Comment by mrcflorian** [comment]
@merovic This is weird. Can you post a screenshot of the Xcode project including all those files? It does seem that you actually haven't included the Core folder after all...

**Comment by merovic** [comment]
<img width="1662" alt="Screen Shot 2019-04-06 at 3 29 26 PM" src="https://user-images.githubusercontent.com/11374760/55670126-cd018d80-5880-11e9-90ae-3057884af7ed.png">

**Comment by chakeel** [comment]
@merovic you haven't pulled core into your folder properly - remove the 'Core' folder from your project and drag it back in again. When you drag it in, select 'create groups' instead of 'create folder references'

let me know if that works :)

**Comment by DuyBui297** [comment]
Looks like this issue has been fixed, let us know if it happens again
